### PR TITLE
Adding ability to run the Doclet on a single repository

### PR DESCRIPTION
**Pull request by runemadsen**
This PR changed the `doclet/ReferenceGenerator/processingrefBuild.sh` script to make it work with an argument to run the script on only a single repository. The following calls are now possible:

```
$ ./processingrefBuild.sh
$ ./processingrefBuild.sh processing
$ ./processingrefBuild.sh sound
$ ./processingrefBuild.sh video
```

This is helpful as we begin to update the content on the new website. The `README.md` file has also been updated to reflect these changes.

### CODE REVIEW

**Comment by benfry** [comment]
Looks like this needs to be rebased.

**Comment by benfry** [comment]
@Anadroid @runemadsen can this one be closed or do we need an update?

**Comment by runemadsen** [comment]
Sorry about the late reply @benfry. The PR is now up to date with `master`, and we pushed a few tweaks to the JavaDoc comments. Merge away if it looks okay to you.

**Comment by benfry** [comment]
Looks good; thanks!

**Pull request merged**
