### PR TITLE
Implementation language server

### PR DESCRIPTION
**Pull request by kgtkr**
#117

This is a rewrite in java of something I made in the past
https://github.com/kgtkr/processing-language-server

client:
https://github.com/kgtkr/processing-language-server-vscode/tree/integrate-pls

image
image

### CODE REVIEW

**Comment by benfry** [comment]
Very cool, thanks for looking into it and even producing this PR. I haven't had a chance to spend enough time looking into it, but hope to soon. Sorry for the delay!

**Comment by sampottinger** [comment]
Thanks for this @kgtkr! Certainly keeping an eye on this PR. Exciting times!

**Comment by benfry** [comment]
I'm trying to keep the 4.0.2 release to bug fixes, but hope to get this incorporated in a release soon. Apologies for the continued delay; just overbooked here.

**Comment by benfry** [comment]
@kgtkr Can you create a fresh PR with only the source code changes, skipping the changes to other build files and the rest? (i.e. just everything inside `processing/mode/java`) and I'll take care of incorporating the other jar/build/ignore file changes separately. Thanks!

**Comment by benfry** [comment]
Never mind that; just gonna merge and try to roll those files back…

**Comment by benfry** [comment]
Ok, we're now merged with a few changes… This will be part of Processing 4.1 (arriving later today or Monday).

A few things were moved around, and the `main()` is now part of `processing.mode.java.lsp.PdeLanguageServer`.

@kgtkr I'm still using the 0.12.0 version of lsp4j that you had included, but the latest seems to be 0.19. Was there a reason you used the older version, or is it just because you wrote the code a while back and hadn't bothered to update to 0.19?

Still lots to be done, but good to have these pieces in place so that others might be able to help improve.

**Comment by kgtkr** [comment]
@benfry
There's no reason to use an older version. i forgot to update the library.

**Comment by benfry** [comment]
Ok thanks, bumping it to 0.19 in that case.

**Comment by kgtkr** [comment]
I've tried Processing4.1 but it seems to be missing a dependency
According to ivy, the full list of required dependencies is below. However, if add only gson, an error message will appear, but it seems to work.

```
[ivy:retrieve]  found org.eclipse.lsp4j#org.eclipse.lsp4j;0.19.0 in public
[ivy:retrieve]  found org.eclipse.lsp4j#org.eclipse.lsp4j.generator;0.19.0 in public
[ivy:retrieve]  found org.eclipse.lsp4j#org.eclipse.lsp4j.jsonrpc;0.19.0 in public
[ivy:retrieve]  found com.google.code.gson#gson;2.9.1 in public
[ivy:retrieve]  found org.eclipse.xtend#org.eclipse.xtend.lib;2.28.0 in public
[ivy:retrieve]  found org.eclipse.xtext#org.eclipse.xtext.xbase.lib;2.28.0 in public
[ivy:retrieve]  found com.google.guava#guava;30.1-jre in public
[ivy:retrieve]  found com.google.guava#failureaccess;1.0.1 in public
[ivy:retrieve]  found com.google.guava#listenablefuture;9999.0-empty-to-avoid-conflict-with-guava in public
[ivy:retrieve]  found com.google.code.findbugs#jsr305;3.0.2 in public
[ivy:retrieve]  found org.checkerframework#checker-qual;3.5.0 in public
[ivy:retrieve]  found com.google.errorprone#error_prone_annotations;2.3.4 in public
[ivy:retrieve]  found com.google.j2objc#j2objc-annotations;1.3 in public
[ivy:retrieve]  found org.eclipse.xtend#org.eclipse.xtend.lib.macro;2.28.0 in public
```

**Comment by benfry** [comment]
Nuts, ok—with `gson.jar` in there it's working for me. But I don't have your client running so I can't say whether everything works. Can you test and let me know? When you confirm, I can post 4.1.1.

If there are new issues that need to be fixed, go ahead and open a new issue so that we can track and reference them properly.

**Comment by kgtkr** [comment]
I'm testing using this I made in the past
https://github.com/kgtkr/processing-language-server-vscode


I've verified that formatting, error reporting and completion work on the main branch. Thank you

**Comment by benfry** [comment]
Excellent, thanks. Will re-post…

**Comment by benfry** [comment]
Ok, 4.1.1 now on the releases page: https://github.com/processing/processing4/releases

**Comment by kgtkr** [comment]
Thank you. I was able to confirm that it works with the latest release.

**Comment by benfry** [comment]
Great, thanks!

**Pull request merged**
