### PR TITLE
Fix broken PNG saving on JAVA2D Mode

### LINKED ISSUE #80: Saving to PNG broken in anything but the default renderer
It looks like the `tiff` extension is always appended even if the requested filename ends in `.png` when using `JAVA2D`. Looks related to the recent refactor on AWT related code.

### PR DESCRIPTION
**Pull request by sampottinger**
Refactor non-tiff image saving logic to allow `PImage` to save PNGs from the `save()` method. Resolves #80.

### CODE REVIEW

**Comment by sampottinger** [comment]
Blocked on #74.

**Comment by sampottinger** [comment]
Just a quick update here... It looks like even in [JavaFX](http://java-buddy.blogspot.com/2013/04/save-canvas-to-png-file.html) and [JOGL](https://stackoverflow.com/questions/22839899/how-to-save-am-image-of-a-screen-using-jogl), BufferedImage is still the canonical solution. There might not be a way to avoid using it.

**Comment by sampottinger** [comment]
[This may be true for LWJGL as well](http://forum.lwjgl.org/index.php?topic=6713.0) but not sure?

**Comment by sampottinger** [comment]
Hey there! There's a few PRs outstanding (with inter-dependencies) and the build on master has been broken on Mac for some time. So, I have an integration branch over at https://github.com/sampottinger/processing4 master. That branch includes this PR. This allows one to use Processing 4 again on a Mac along with all of the recent bug fixes. For your convenience, I have made builds available at https://www.datadrivenempathy.com/processing.

**Comment by sampottinger** [comment]
Hey there! There's a few PRs outstanding (with inter-dependencies) and the build on master has been broken on Mac for some time. So, I have an integration branch over at https://github.com/sampottinger/processing4 master. That branch includes this PR. This allows one to use Processing 4 again on a Mac along with all of the recent bug fixes. For your convenience, I have made builds available at https://www.datadrivenempathy.com/processing.

**Comment by benfry** [comment]
See notes in #80.

**Pull request closed without merging**
