### PR TITLE
Add language support to modes

### PR DESCRIPTION
**Pull request by codeanticode**

### CODE REVIEW

**Comment by sampottinger** [comment]
Hey @codeanticode! Thank you for this PR. I think this is based off of #12. Is that correct? @benfry I think that's why this PR looks larger.

**Comment by benfry** [comment]
Yeah, a rebase might be a good idea…

**Comment by sampottinger** [comment]
Hey @codeanticode! Really sorry about the noise from my PRs recently. I did just double check that everything is still OK after all the merges came together (https://github.com/sampottinger/processing4/pull/18). Let me know if there's anything I can do to help and thanks for your patience / hard work.

**Comment by codeanticode** [comment]
I don't mind getting updates, great to sees so much progress happening!

**Comment by sampottinger** [comment]
Hey @codeanticode, just checking back in. Is there anything I can do to help with this PR? I have also been testing with this merged into master at https://github.com/sampottinger/processing4. Everything seems fine! :D

**Comment by codeanticode** [comment]
@sampottinger I haven't looked again into it, the current changes enabling language support for modes are fairly minor, but I now remembered that we may need a way to ensure that a string provided in a mode's language file does not overwrite an existing string from base... so I'd need to come back to this and probably create a new PR incorporating with such safeguards.

**Comment by benfry** [comment]
@codeanticode Ok, when that updated version is ready I'll give it a merge.

**Comment by codeanticode** [comment]
Continuing this work in a new fork, I will reopen once it's finalized.

**Pull request closed without merging**
