### PR TITLE
Fast forward JSSC

### LINKED ISSUE #525: Need to update to the latest JSSC to work on Apple M1
Platform: macOS Monterey 12.4 Apple M1.
Issue Description: Processing 4.0b8 is having issue with incompatible JSSC library.
The Fix/Solution: Grab the latest JSSC jar file (as of this writing, v2.9.4) and overwrite the existing jssc.jar within Processing.app.
Step to Reproduce: Open and run SimpleRead example throws an error that JSSC is not available.

### PR DESCRIPTION
**Pull request by sampottinger**
Fixes #525.

### CODE REVIEW

**Comment by sampottinger** [comment]
Tested on Intel Mac. Need to test on Linux, Windows, and Mac M1. Luckily java-native upstream uses a fat jar now so distribution is easier but I think we may still need https://github.com/sampottinger/jssc due to the properties and path stuff.

**Comment by sampottinger** [comment]
Still don’t have access to an M1 but working on Intel Mac, Windows, and Linux!

**Comment by hkiel** [comment]
I have an M1. What exactly is to check? Can you provide a Processing binary distribution for the test?

**Comment by sampottinger** [comment]
Let me see if I can make a build. Thanks!

**Comment by sampottinger** [comment]
Got my hands on an m1 and there is a path issue there. Working through it now.

**Comment by sampottinger** [comment]
Good news! https://github.com/sampottinger/jssc/pull/9 appears to have fixed it on M1. The only bummper is we are getting SLF4J logging noise :(

Will address that after testing this on linux and windows. Good to go on Mac (M1 and Intel)

**Comment by sampottinger** [comment]
Linux and Windows look good. Just addressing the SLF4J situation in JSSC.

**Comment by sampottinger** [comment]
Sorry about that @benfry. Now working on both macs (intel, M1), windows, and linux.

**Comment by benfry** [comment]
Thanks! Now merged for 4.0.2.

**Pull request merged**
