### PR TITLE
Revert to 11.0.6 to restore JOGL rendering.

### LINKED ISSUE #121: P3D Rendering Blank
Looking into this now... weirdly I don't see it happening on the integration branch over at https://github.com/sampottinger/processing4/. 

*Edit:* It turns out that it fails when bumping past JDK 11.0.6. Reverting to 11.0.6 restores expected behavior.

Screen Shot 2020-08-16 at 8 13 42 PM

### PR DESCRIPTION
**Pull request by sampottinger**
Ugghhhh 😑. Up for some discussion but going beyond 11.0.6 seems to break JOGL rendering. Resolves #121.

### CODE REVIEW

**Comment by benfry** [comment]
!(#@$*& so it looks like 11.0.6 isn't signed properly, so now we're back up to 304 notarization errors for every last `.dylib` and binary inside the JDK directory.

**Comment by benfry** [comment]
…so alpha 2 is held up until we can figure out what's going on with this GL stuff.

**Comment by sampottinger** [comment]
Dang :( ok I’ll try to dig into this as soon as I can.

**Comment by benfry** [comment]
Also wondering if it's a JOGL issue or if there's an update there…

**Comment by sampottinger** [comment]
Yeah it's possible @benfry. I am going to try to look into it a bit today.

**Comment by sampottinger** [comment]
Just opened #124

**Pull request merged**
