### PR TITLE
Moved fbo allowed check into PGL.

### LINKED ISSUE #50: “WARNING: Illegal reflective access by processing.opengl.PSurfaceJOGL” on getContextCapabilities()
This is not the same as https://github.com/processing/processing4/issues/22, which is another `WARNING: Illegal reflective access` message.

Due to the workaround for https://github.com/processing/processing/issues/4104, we've got a reflection hack that spews a big warning.

The hack involves getting the name of the hardware so that we can add a workaround for `Intel HD Graphics 3000` devices. 

Not sure if we're free to nix the hack for 4.x (though it only recently went into 3.x), or perhaps there's another way to get hardware information.

### PR DESCRIPTION
**Pull request by sampottinger**
Move checking for frame buffer object support from `PSurfaceJOGL` to `PGL`, closing a TODO in `PGL` and removing dependency on reflexive access. This is done by switching to resolving the check on demand after renderer has initialized. Note that this does require subclasses of `PGL` to use or override `getIsFboAllowed` instead of direct access to `fboAllowed`. This will require checking in with @benfry.
    
Resolves #50.

### CODE REVIEW

**Comment by sampottinger** [comment]
Note that this is blocked on #74.

**Comment by sampottinger** [comment]
Hey there! There's a few PRs outstanding (with inter-dependencies) and the build on master has been broken on Mac for some time. So, I have an integration branch over at https://github.com/sampottinger/processing4 master. That branch includes this PR. This allows one to use Processing 4 again on a Mac along with all of the recent bug fixes. For your convenience, I have made builds available at https://www.datadrivenempathy.com/processing.

**Comment by benfry** [comment]
Alternate solution based on this work now here: https://github.com/processing/processing4/commit/cc39c94d1dd9b7877207a5a0334620248b60371e Thanks for your help!

**Comment by sampottinger** [comment]
Just re-opening and merging but with no changes to master to make it easier for dependent PRs

**Pull request merged**
