### PR TITLE
Various fixes for preproc

### LINKED ISSUE #602: size(863,863/2) not working as first line of setup() function in a simple sketch
When running one of Dan Shiffman's examples, it failed on the size(863,863/2); line in the setup(). The error said to look at the documentation for the size() function. The only requirement was for the size() function to be in the setup() function as the first line and for it to be in the processing sketch named the same.

However, it appears the size() can't have arithmetic expressions as part of the argument list.

 

## Description

When running one of Dan Shiffman's  mandelbrot example sketch, it failed on the size(863,863/2); statement in the setup() function. The error said to look at the documentation for the size() function. 

The documentation for size():
- size() function must be in the setup() function as the first line 
- and for size() to be in the main processing sketch.

However, it appears the size() can't have arithmetic expressions as part of the argument list.

## Expected Behavior

expected the size(863,863/2); to work or with integer variables as arguments 

## Current Behavior

sketch won't run, error messages says size() can't be used here, changing it to size(863,431); got it to work.

## Steps to Reproduce

1. include a size(863,863/2) as the first statement in the setup() function of a simple sketch
2. 
```java
void setup() {
    size(863,863/2);
}
void draw() {

}
```
3. run program
4. should see error below sketch code

## Your Environment

 

* Processing version: 4.0.1
* Operating System and OS version: MacOS 10.13 Ventura
* Other information: Running on a macmini with Apple M1 chip

## Possible Causes / Solutions

workaround is to do the sizing math and keep size(863,431); arguments as simple integer constants. 

provide a better error message that points to the arguments as not being simple integers.

### PR DESCRIPTION
**Pull request by sampottinger**
Addresses some small misc issues in preproc…

 - Closes #602. It will not rewrite if there is a method call or call with variable, passing up to compiler to determine if it is still valid. This is required because of someone overloading size or implementing their own (see #317).
 - Most of #607. See below.

### CODE REVIEW

**Comment by sampottinger** [comment]
@benfry - addressed #602 but looking at #607

**Comment by sampottinger** [comment]
@benfry - I was able to get most of this sorted except for indent. The problem is I have to keep the EDT and Javac in sync with each other when edits are made by preproc so errors and warnings go to the right place when they try to find token locations. However, newlines are not tokens on their own in Antlr. So, doing that indent will take a little more thought to ensure I don’t introduce any new bugs.

I’d recommend merging this without the indent fix and addressing indent in a separate PR.

**Comment by benfry** [comment]
Ok, the indent fix is more about avoiding the extra space before each `public` seen here:

Screen Shot 2022-11-27 at 7 56 13 PM

I'm far less worried about adding indents (especially if ANTLR isn't giving you newlines, I totally get that), but we shouldn't be adding extra spaces in there.

**Comment by sampottinger** [comment]
@benfry - Sorry for the confusion. I think the extra space in front was resolved!

**Comment by benfry** [comment]
Perfect, thanks!

**Comment by benfry** [comment]
And https://github.com/processing/processing4/issues/519 is still open, right? (Totally fine, just wrapping up the release here.)

**Comment by sampottinger** [comment]
Yes #519 is still open. :(

**Comment by benfry** [comment]
No problem, thanks again.

**Pull request merged**
