### PR TITLE
Parameterize preprocessor behavior to allow mode overrides.

### PR DESCRIPTION
**Pull request by sampottinger**
In response to processing#11, allow client code to override preprocessing edit behavior by providing a subclass of PdeParseTreeListener. Specifically, given the changes necessitated by #1's swtich to ANTLR 4, this PR formalizes the interfaces to parameterize that behavior and adjusts internal code to improve mode developer experience.

For a demonstration of this new interface (prepared for @codeanticode) please see https://gist.github.com/sampottinger/11c453f5f641d96b4244f947d93cca33.

Note that many of the small interfaces were refactored to keep consistent with @benfry's goal for low class count.

### CODE REVIEW

**Comment by sampottinger** [comment]
Hey @monkstone! Not 100% sure but this may be relevant to your work as well? See #11. Thanks!

**Comment by monkstone** [comment]
@sampottinger Thanks for heads up, but I never tried to create a ruby mode for the Processing Ide @tyfkda did [here](https://github.com/tyfkda/processing-ruby-mode).  I have instead created an [atom plugin]( https://ruby-processing.github.io/atom-k9).

**Comment by sampottinger** [comment]
Thanks for the clarification @monkstone

**Comment by sampottinger** [comment]
Quick thing: Trying to remove `RewriteParams` by rolling it into `PdeParseTreeListener`. Do not merge until I have a chance to do that.

**Comment by sampottinger** [comment]
RewriteParams rolled into PdeParseTreeListener (per low class count target for project). Ok to merge again.

**Comment by codeanticode** [comment]
@sampottinger quick question, where is the ProcessingBaseListener base class that [PdeParseTreeListener](https://github.com/sampottinger/processing4/blob/master/java/src/processing/mode/java/preproc/PdeParseTreeListener.java#L47) extends?

**Comment by codeanticode** [comment]
Never mind, I just realized it is generated during the build :-)

**Comment by sampottinger** [comment]
> where is the ProcessingBaseListener base class that PdeParseTreeListener extends?

Hey @codeanticode! Thanks for following up. Just for progeny, you are correct about `ProcessingBaseListener` and it is part of the Listener pattern-based infrastructure of ANTLR 4 as described at https://github.com/antlr/antlr4/blob/master/doc/listeners.md.

**Comment by sampottinger** [comment]
Also @codeanticode, https://github.com/processing/processing4/pull/13/commits/fdcaf7d932e80ee87979dfd0b509b09e3ca9a9e5 addresses your request. It can be used like so:

```
PdePreprocessor.builderFor(sketchName)
        .setParseTreeListenerFactory(...)
        .setDestinationPackage("com.someone.somwhere")
        .build();
```

This should keep the ANTLR types from leaking out into modes unless they need to modify the edit behavior at a deeper level.

Thank you for your hard work. Please let me know if there is more that I can do.

Thanks,
Sam

**Pull request merged**
