### PR TITLE
support for pde:// browser protocol (LINUX)

### LINKED ISSUE #674: Register `pde://` browser protocol for .pdez and .pdex files on Linux
Starting with Processing 4.2, you can use `pde://` URLs to open `.pdex` and `.pdez` files from the internet and the local machine (see #559). These are implemented on macOS and Windows, but I ran out of time to implement and test them properly on Linux.

To implement, the necessary incantations should be added to the Linux install script. [This](https://unix.stackexchange.com/a/497147) looks like a reasonably up to date resource on how to make it happen. Or [this](https://web.archive.org/web/20210601082308/https://support.shotgunsoftware.com/hc/en-us/articles/219031308-How-to-launch-external-applications-using-custom-protocols-rock-instead-of-http-?mobile_site=true) older document was used as the basis for the Windows and macOS versions, and includes a Linux implementation as well. 

Please help!

### PR DESCRIPTION
**Pull request by zriqo**
I have added the support of pde:// browser protocol for linux(Fixes: https://github.com/processing/processing4/issues/674 )
which enables the opening of *.pde file from web URLs using the pde:// protocol.

as from previous [PR#689](https://github.com/processing/processing4/pull/689) discussion, we still have two undesired behavior-
1. on executing `xdg-open pde:///path/to/sketchbook/SimpleExport/SimpleExport.pde` it open ups two different window, one with desired file other one with empty file.

2. on visiting `xdg-open pde://sableraf.github.io/testURIscheme/sketchBundle.pdez` it opens  `sketchBundle.pdez` only if processing is already in run.

### CODE REVIEW

**Comment by SableRaf** [comment]
Thanks @lala-lala-lori! Please note that merging your PR may take a little while as we work through other issues. Thanks for your contribution.

**Comment by SableRaf** [comment]
cc @evan-goode since you weighed in on the previous version of this contribution, would you mind having a look at this new Pull Request? Thanks!

**Comment by evan-goode** [comment]
LGTM!
These underlying cause of these issues

>on executing xdg-open pde:///path/to/sketchbook/SimpleExport/SimpleExport.pde it open ups two different window, one with desired file other one with empty file.

>on visiting xdg-open pde://sableraf.github.io/testURIscheme/sketchBundle.pdez it opens sketchBundle.pdez only if processing is already in run.

seem to be unrelated to the changes made in this PR.

**Comment by sampottinger** [comment]
Thanks for this contribution @lala-lala-lori !

**Comment by benfry** [comment]
Awesome, thank you! This is merged for 4.3.

**Pull request merged**
