### PR TITLE
Scale by pixel density to coordinates are consistent

### LINKED ISSUE #429: filter() incompatible with high pixel density on P2D and P3D
## Description

Using `filter()` (for example, `filter(GRAY)`, `filter(INVERT)`) in combination with a higher pixel density (set for example with `pixelDensity(displayDensity())`) behaves weirdly when using P2D or P3D.

## Expected Behavior

The filter would be applied with P2D/P3D and high pixel density in the same way as with the default renderer or with default pixel density.

## Current Behavior

The frame is drawn zoomed in on the top left corner. If the default renderer is used, everything works as expected. If no higher pixel density is used, everything works as expected. Interestingly, if we use `saveFrame()`, the saved image looks fine even though it is rendered wrong in Processing. Therefore, I'm attaching here screenshots instead of saved frames.

Default renderer or default pixel density:
Captura de pantalla 2022-03-02 a las 12 37 44

High pixel density and P2D/P3D:
Captura de pantalla 2022-03-02 a las 12 37 31

## Steps to Reproduce

1. Set P2D or P3D as the renderer.
2. Set a high pixel density.
3. Use `filter()`.

```
void setup() {
  size(500, 500, P3D);
  pixelDensity(displayDensity());
  rectMode(CENTER);
  noLoop();
  
  background(0);
  noStroke();
  fill(255, 0, 0);
}

void draw() {
  rect(width*0.5, height*0.5, width*0.5, height*0.5);
  filter(GRAY);
}
```

## Your Environment

 

* Processing version: Processing 4.0b6 (x64)
* Operating System and OS version: macOS 12.2.1
* Other information: Apple M1 chip

### PR DESCRIPTION
**Pull request by codeanticode**
This fixes https://github.com/processing/processing4/issues/429 but has not been tested extensively

### CODE REVIEW

**Comment by benfry** [comment]
Just to be clear, the behavior should be that there are 2x the pixels in either direction, so was the problem just a scaling issue? (i.e. we don't want to just take low-res buffers and scale them larger… `pixelDensity(2)` means all pixel operations live in a 2x space (`pixelWidth` and `pixelHeight` instead of `width` and `height`)

**Comment by codeanticode** [comment]
I think the coordinate scaling is the correct solution because the issue is caused by the texture backing the drawing surface having double the size being rendered on window coordinates...

But, this rescaling should be done only if we are applying copy to a backing surface texture, not a regular image. This is, when copy(PImage src...) is called from copy(int sx, int sy...)

**Comment by codeanticode** [comment]
@benfry  just realized that any PImage contains its own pixelDensity so maybe the last commit fixed properly the issue? We would need to test more, because this change may have unintended consequences :-)

**Comment by benfry** [comment]
Yeah, this seems more correct. Let me know what you find out with testing, and I can merge if you think it's stable and working. Or if you have high confidence now, I can merge and hopefully someone using the source might catch issues before any release.

**Comment by codeanticode** [comment]
I will do some testing with the filter function, hopefully this fixes the issue without any side effects.

**Comment by benfry** [comment]
Thanks!

**Pull request merged**
