### PR TITLE
Use getMainName on PreprocService

### LINKED ISSUE #610: Processing doesn't recognize methods of PApplet when the sketchfolder has a hyphen in it
## Description

When the name of a sketch folder contains a hyphen, Processing doesn't recognize the methods of `PApplet` like `draw()`, `background()`, etc.
The sketch will compile and run without any problems anyway.

## Steps to Reproduce

1. Create a sketch in a folder with a name containing a hyphen
2. A `sketch.properties` file is created pointing to the main file (which can't have a hyphen in it, Processing will refuse to start in that case)
3. Processing won't recognize the methods of `PApplet` anymore (`draw()`, `background()`, etc.)

## Your Environment

 

* Processing version: 4.1.1
* Operating System and OS version: TUXEDO OS 1 (KDE Plasma) / Windows 11
* Other information: This problem exists since 4.1.0

### PR DESCRIPTION
**Pull request by sampottinger**
Fixes #610.

Screenshot 2023-01-15 at 7 45 45 PM

### CODE REVIEW

**Comment by sampottinger** [comment]
I think this is working for me (I ran your example) but wouldn't hurt if you checked that it looked ok on your end @benfry. Thanks!

**Comment by sampottinger** [comment]
Tried a few different “bad” sketch names and this is still working. This change should align the behavior in preproc service to the full build. Thanks for your patience!

**Comment by mythicaleinhorn** [comment]
I can also check this later today with the sketch where the problem first occurred for me. But this looks very good! Thank you 🙏

**Comment by benfry** [comment]
Awesome; thanks. At some point last night I woke up and was like “oh, it's `getMainName()` vs `getName()`… that's the whole point of adding `getMainName()`” but was too dumb to make the connection earlier in the day. 

Appreciate the help!

**Pull request merged**
